/*
 * The MIT License
 *
 * Copyright 2019 Rodrigo Ferreira Rodrigues <https://github.com/rfrodriguespe>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.rftech.view;

import br.com.rftech.Dao.ChamadoJpaDao;
import br.com.rftech.Dao.ClientePfJpaDao;
import br.com.rftech.Dao.NotebookJpaDao;
import br.com.rftech.bean.Chamado;
import br.com.rftech.bean.ChamadoTableModel;
import br.com.rftech.bean.ClientePf;
import br.com.rftech.bean.Notebook;
import br.com.rftech.bean.TableColumnAdjuster;
import java.util.Calendar;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rodrigo Ferreira Rodrigues <https://github.com/rfrodriguespe>
 */
public class ChamadoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientesPFView
     */
    public ChamadoView() {
        initComponents();
        jTableChamado.setModel(tableModel);
        preencheTabela();
        populaComboBoxes();
        habilitaCampos(false);
    }

    //Instancia minha jTable com base no modelo de Tabela definido no pacote MODEL
    ChamadoTableModel tableModel = new ChamadoTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneChamados = new javax.swing.JTabbedPane();
        jPanelConsulta = new javax.swing.JPanel();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableChamado = new javax.swing.JTable();
        jPanelAcoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelAbertura = new javax.swing.JPanel();
        jPanelDadosChamado = new javax.swing.JPanel();
        tfId = new javax.swing.JTextField();
        jLabelFabricante = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelDono = new javax.swing.JLabel();
        cbDono = new javax.swing.JComboBox<>();
        jLabelModelo = new javax.swing.JLabel();
        cbEquipamento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDefeitoRelatado = new javax.swing.JTextArea();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonLimpar = new javax.swing.JButton();
        btAbrirChamado = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFecharJanela = new javax.swing.JButton();
        jPanelFechamento = new javax.swing.JPanel();
        jPanelDadosChamado1 = new javax.swing.JPanel();
        tfId1 = new javax.swing.JTextField();
        jLabelId1 = new javax.swing.JLabel();
        jLabelDono1 = new javax.swing.JLabel();
        cbChamadosAbertos = new javax.swing.JComboBox<>();
        jLabelModelo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAbaFechamentoDefeitoRelatado = new javax.swing.JTextArea();
        jLabelModelo2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taAbaFechamentoDefeitoConstatado = new javax.swing.JTextArea();
        jLabelModelo3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taAbaFechamentoSolucao = new javax.swing.JTextArea();
        jPanelBotoes1 = new javax.swing.JPanel();
        jButtonLimpar1 = new javax.swing.JButton();
        btFechaChamado = new javax.swing.JButton();
        btAtendeChamado = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        btAbaEncerramentoFechaJanela = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(787, 412));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Chamados"));

        jTableChamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HP", "Garantia pelo Fabricante"}
            },
            new String [] {
                "Cód", "Fabricante", "Obs"
            }
        ));
        jTableChamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableChamadoMouseClicked(evt);
            }
        });
        jTableChamado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableChamadoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableChamado);

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcoesLayout = new javax.swing.GroupLayout(jPanelAcoes);
        jPanelAcoes.setLayout(jPanelAcoesLayout);
        jPanelAcoesLayout.setHorizontalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAcoesLayout.setVerticalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelTabela.getAccessibleContext().setAccessibleName("Dados Pessoais");

        jTabbedPaneChamados.addTab("Consulta", jPanelConsulta);

        jPanelDadosChamado.setBorder(javax.swing.BorderFactory.createTitledBorder("Abertura de Chamado"));
        jPanelDadosChamado.setPreferredSize(new java.awt.Dimension(787, 412));

        tfId.setEditable(false);

        jLabelFabricante.setText("Equipamento:");

        jLabelId.setText("ID:");

        jLabelDono.setText("Cliente:");

        cbDono.setEnabled(false);

        jLabelModelo.setText("Defeito Relatado:");

        cbEquipamento.setEnabled(false);

        taDefeitoRelatado.setColumns(20);
        taDefeitoRelatado.setLineWrap(true);
        taDefeitoRelatado.setRows(5);
        taDefeitoRelatado.setToolTipText("Descreve o problema do Equipamento");
        taDefeitoRelatado.setEnabled(false);
        jScrollPane1.setViewportView(taDefeitoRelatado);

        javax.swing.GroupLayout jPanelDadosChamadoLayout = new javax.swing.GroupLayout(jPanelDadosChamado);
        jPanelDadosChamado.setLayout(jPanelDadosChamadoLayout);
        jPanelDadosChamadoLayout.setHorizontalGroup(
            jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                        .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelFabricante))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEquipamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelDadosChamadoLayout.setVerticalGroup(
            jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDono)
                    .addComponent(cbDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabricante)
                    .addComponent(cbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButtonLimpar.setText("Limpar Campos");
        jButtonLimpar.setEnabled(false);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        btAbrirChamado.setText("Abrir Chamado");
        btAbrirChamado.setEnabled(false);
        btAbrirChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirChamadoActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFecharJanela.setText("Fechar");
        jButtonFecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharJanelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbrirChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFecharJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbrirChamado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharJanela)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jPanelAberturaLayout = new javax.swing.GroupLayout(jPanelAbertura);
        jPanelAbertura.setLayout(jPanelAberturaLayout);
        jPanelAberturaLayout.setHorizontalGroup(
            jPanelAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosChamado, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanelAberturaLayout.setVerticalGroup(
            jPanelAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAberturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDadosChamado, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addGap(328, 328, 328))
        );

        jTabbedPaneChamados.addTab("Abertura de Chamados", jPanelAbertura);

        jPanelDadosChamado1.setBorder(javax.swing.BorderFactory.createTitledBorder("Encerramento"));
        jPanelDadosChamado1.setPreferredSize(new java.awt.Dimension(787, 412));

        tfId1.setEditable(false);

        jLabelId1.setText("ID:");

        jLabelDono1.setText("Chamados");

        cbChamadosAbertos.setEnabled(false);
        cbChamadosAbertos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbChamadosAbertosItemStateChanged(evt);
            }
        });

        jLabelModelo1.setText("Defeito Relatado:");

        taAbaFechamentoDefeitoRelatado.setColumns(20);
        taAbaFechamentoDefeitoRelatado.setLineWrap(true);
        taAbaFechamentoDefeitoRelatado.setRows(5);
        taAbaFechamentoDefeitoRelatado.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechamentoDefeitoRelatado.setEnabled(false);
        jScrollPane3.setViewportView(taAbaFechamentoDefeitoRelatado);

        jLabelModelo2.setText("Defeito Constatado");

        taAbaFechamentoDefeitoConstatado.setColumns(20);
        taAbaFechamentoDefeitoConstatado.setLineWrap(true);
        taAbaFechamentoDefeitoConstatado.setRows(5);
        taAbaFechamentoDefeitoConstatado.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechamentoDefeitoConstatado.setEnabled(false);
        jScrollPane4.setViewportView(taAbaFechamentoDefeitoConstatado);

        jLabelModelo3.setText("Solução");

        taAbaFechamentoSolucao.setColumns(20);
        taAbaFechamentoSolucao.setLineWrap(true);
        taAbaFechamentoSolucao.setRows(5);
        taAbaFechamentoSolucao.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechamentoSolucao.setEnabled(false);
        jScrollPane5.setViewportView(taAbaFechamentoSolucao);

        javax.swing.GroupLayout jPanelDadosChamado1Layout = new javax.swing.GroupLayout(jPanelDadosChamado1);
        jPanelDadosChamado1.setLayout(jPanelDadosChamado1Layout);
        jPanelDadosChamado1Layout.setHorizontalGroup(
            jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosChamado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelo1)
                    .addComponent(jLabelModelo2)
                    .addGroup(jPanelDadosChamado1Layout.createSequentialGroup()
                        .addComponent(jLabelId1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDono1))
                    .addComponent(jLabelModelo3))
                .addGap(12, 12, 12)
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addComponent(cbChamadosAbertos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanelDadosChamado1Layout.setVerticalGroup(
            jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosChamado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId1)
                    .addComponent(tfId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDono1)
                    .addComponent(cbChamadosAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelo1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelo2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelo3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanelBotoes1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButtonLimpar1.setText("Limpar Campos");
        jButtonLimpar1.setEnabled(false);
        jButtonLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpar1ActionPerformed(evt);
            }
        });

        btFechaChamado.setText("Fechar Chamado");
        btFechaChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechaChamadoActionPerformed(evt);
            }
        });

        btAtendeChamado.setText("Atender Chamado");
        btAtendeChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtendeChamadoActionPerformed(evt);
            }
        });

        jButtonCancelar1.setText("Cancelar");
        jButtonCancelar1.setEnabled(false);
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });

        btAbaEncerramentoFechaJanela.setText("Fechar");
        btAbaEncerramentoFechaJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaEncerramentoFechaJanelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoes1Layout = new javax.swing.GroupLayout(jPanelBotoes1);
        jPanelBotoes1.setLayout(jPanelBotoes1Layout);
        jPanelBotoes1Layout.setHorizontalGroup(
            jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoes1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLimpar1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btAtendeChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFechaChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbaEncerramentoFechaJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoes1Layout.setVerticalGroup(
            jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAtendeChamado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechaChamado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAbaEncerramentoFechaJanela)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jPanelFechamentoLayout = new javax.swing.GroupLayout(jPanelFechamento);
        jPanelFechamento.setLayout(jPanelFechamentoLayout);
        jPanelFechamentoLayout.setHorizontalGroup(
            jPanelFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFechamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosChamado1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanelFechamentoLayout.setVerticalGroup(
            jPanelFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFechamentoLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanelFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDadosChamado1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(221, 221, 221))
        );

        jTabbedPaneChamados.addTab("Fechamento de Chamados", jPanelFechamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // Limpa os campos
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void btAbrirChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirChamadoActionPerformed
        if (!CamposEmBranco()) {
            Notebook notebook = NotebookJpaDao.getInstance().getById(cbEquipamento.getSelectedIndex() + 1);
            String defeitoRelatado = taDefeitoRelatado.getText();
            Chamado chamado = new Chamado(notebook, defeitoRelatado);
            if (ChamadoJpaDao.getInstance().create(chamado)) {
                JOptionPane.showMessageDialog(this, "Chamado aberto com sucesso");
                preencheTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao abrir chamado");
            }
        }
    }//GEN-LAST:event_btAbrirChamadoActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        habilitaCampos(true);
        habilitaBotoes(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        habilitaBotoes(false);
        habilitaCampos(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableChamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableChamadoMouseClicked
        // TODO add your handling code here:
        populaCamposByJTable();
    }//GEN-LAST:event_jTableChamadoMouseClicked

    private void jButtonFecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharJanelaActionPerformed

    private void jTableChamadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableChamadoKeyPressed
        // TODO add your handling code here:
        populaCamposByJTable();
    }//GEN-LAST:event_jTableChamadoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpar1ActionPerformed

    private void btFechaChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechaChamadoActionPerformed
        // TODO add your handling code here:
        if (cbChamadosAbertos.getSelectedIndex() != -1){
            Chamado chamadoAt = ChamadoJpaDao.getInstance().getById(Integer.parseInt(tfId1.getText()));
            chamadoAt.setDefeitoConstatado(taAbaFechamentoDefeitoConstatado.getText());
            chamadoAt.setSolucao(taAbaFechamentoSolucao.getText());
            chamadoAt.setDataFechamento(Calendar.getInstance().getTime());
            chamadoAt.setStatus(Chamado.FECHADO);
            
            if (ChamadoJpaDao.getInstance().update(chamadoAt)){
                JOptionPane.showMessageDialog(null, "Chamado fechado com sucesso");
                cbChamadosAbertos.removeAllItems();
                getChamadosAbertos();
                tfId1.setText("");
                taAbaFechamentoDefeitoRelatado.setText("");
                taAbaFechamentoDefeitoConstatado.setText("");
                taAbaFechamentoSolucao.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar fechar chamado");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um chamado aberto para fechar");
        }
    }//GEN-LAST:event_btFechaChamadoActionPerformed

    private void btAtendeChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtendeChamadoActionPerformed
        atenderChamado();
    }//GEN-LAST:event_btAtendeChamadoActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void btAbaEncerramentoFechaJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaEncerramentoFechaJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAbaEncerramentoFechaJanelaActionPerformed

    private void cbChamadosAbertosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChamadosAbertosItemStateChanged
        // TODO add your handling code here:
        //Montar Lógica de preencher as coisas...
        if (cbChamadosAbertos.getSelectedIndex() != -1){
            Chamado chAt = (Chamado) cbChamadosAbertos.getSelectedItem();
            tfId1.setText(""+chAt.getId());
            taAbaFechamentoDefeitoRelatado.setText(chAt.getDefeitoRelatado());
        }
    }//GEN-LAST:event_cbChamadosAbertosItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbaEncerramentoFechaJanela;
    private javax.swing.JButton btAbrirChamado;
    private javax.swing.JButton btAtendeChamado;
    private javax.swing.JButton btFechaChamado;
    private javax.swing.JButton btNovo;
    private javax.swing.JComboBox<Chamado> cbChamadosAbertos;
    private javax.swing.JComboBox<String> cbDono;
    private javax.swing.JComboBox<String> cbEquipamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonFecharJanela;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLimpar1;
    private javax.swing.JLabel jLabelDono;
    private javax.swing.JLabel jLabelDono1;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelModelo1;
    private javax.swing.JLabel jLabelModelo2;
    private javax.swing.JLabel jLabelModelo3;
    private javax.swing.JPanel jPanelAbertura;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelBotoes1;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelDadosChamado;
    private javax.swing.JPanel jPanelDadosChamado1;
    private javax.swing.JPanel jPanelFechamento;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPaneChamados;
    private javax.swing.JTable jTableChamado;
    private javax.swing.JTextArea taAbaFechamentoDefeitoConstatado;
    private javax.swing.JTextArea taAbaFechamentoDefeitoRelatado;
    private javax.swing.JTextArea taAbaFechamentoSolucao;
    private javax.swing.JTextArea taDefeitoRelatado;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfId1;
    // End of variables declaration//GEN-END:variables

    private void populaComboBoxes() {

        List<ClientePf> listaClientesPf = ClientePfJpaDao.getInstance().readAll();
        for (ClientePf clientePf : listaClientesPf) {
            cbDono.addItem("Id: " + clientePf.getId() + " Cpf: " + clientePf.getCpf() + " Nome: " + clientePf.getNome());
        }

        List<Notebook> listaNotebooks = NotebookJpaDao.getInstance().readAll();
        for (Notebook notebook : listaNotebooks) {
            cbEquipamento.addItem(notebook.getModelo() + " " + notebook.getSerial());
        }
    }

    public void preencheTabela() {
        limpaTabela();
        List<Chamado> listaChamado = ChamadoJpaDao.getInstance().readAll();
        listaChamado.forEach((chamado) -> {
            tableModel.addRow(chamado);
        });
        jTableChamado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTableChamado);
        tca.adjustColumns();
    }

    public void limpaTabela() {
        tableModel.limpaTabela();
    }

    public void limparCampos() {
        tfId.setText("");
        taDefeitoRelatado.setText("");
    }

    public boolean CamposEmBranco() {
        int erros = 0;
        if (taDefeitoRelatado.getText().equals("")){
            erros++;
        }
        if (erros == 0) {
            return false;
        } else {
            return true;
        }
    }

    private void habilitaCampos(boolean estado) {
        JComboBox[] listaComboBoxes = {cbDono, cbEquipamento};
        for (JComboBox comboBox : listaComboBoxes) {
            comboBox.setEnabled(estado);
        }
        taDefeitoRelatado.setEnabled(estado);
    }

    private void habilitaBotoes(boolean estado) {
        jButtonCancelar.setEnabled(estado);
        jButtonLimpar.setEnabled(estado);
        btAbrirChamado.setEnabled(estado);
    }

    private void populaCamposByJTable() {
        if (jTableChamado.getSelectedRow() != -1) {

//            tfId.setText(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 0).toString());
//            cbDono.setSelectedIndex(Integer.parseInt(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 1).toString()) - 1);
//            EquipamentosTipo tipoEquipamento = (EquipamentosTipo) jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 4);
//            jComboBoxTipoEquipamento.setSelectedIndex(tipoEquipamento.getId() - 1);
//            Fabricante fabricante = (Fabricante) jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 5);
//            cbEquipamento.setSelectedIndex(fabricante.getId() - 1);
//            tfModelo.setText(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 6).toString());
//            tfSerial.setText(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 7).toString());
//            jComboBoxTela.setSelectedItem(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 8));
//            jComboBoxRam.setSelectedItem(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 9));
//            jComboBoxHd.setSelectedItem(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 10));
        }
    }

    private void atenderChamado() {
        getChamadosAbertos();
        cbChamadosAbertos.setEnabled(true);
        taAbaFechamentoDefeitoRelatado.enable(true);
        taAbaFechamentoDefeitoConstatado.enable(true);
        taAbaFechamentoSolucao.enable(true);
        btFechaChamado.setEnabled(true);
    }

    private void getChamadosAbertos() {
        List<Chamado> listaChamadoAbertos = ChamadoJpaDao.getInstance().readAll();
        for (Chamado chamado : listaChamadoAbertos) {
            if (chamado.getStatus().equals(Chamado.ABERTO)) {
                cbChamadosAbertos.addItem(chamado);
            }
        }
    }
}
