/*
 * The MIT License
 *
 * Copyright 2019 Rodrigo Ferreira Rodrigues <https://github.com/rfrodriguespe>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.rftech.view;

import br.com.rftech.Dao.ChamadoJpaDao;
import br.com.rftech.Dao.ClientePfJpaDao;
import br.com.rftech.Dao.NotebookJpaDao;
import br.com.rftech.bean.Chamado;
import br.com.rftech.bean.ChamadoTableModel;
import br.com.rftech.bean.ClientePf;
import br.com.rftech.bean.Notebook;
import br.com.rftech.bean.TableColumnAdjuster;
import java.util.Calendar;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rodrigo Ferreira Rodrigues <https://github.com/rfrodriguespe>
 */
public class ChamadoView extends javax.swing.JInternalFrame {

    public static Chamado chEmAt;

    /**
     * Creates new form ClientesPFView
     */
    public ChamadoView() {
        initComponents();
        jTableChamado.setModel(tableModel);
        habilitaCamposAbaAbrir(false);
    }

    //Instancia minha jTable com base no modelo de Tabela definido no pacote MODEL
    ChamadoTableModel tableModel = new ChamadoTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneChamados = new javax.swing.JTabbedPane();
        jPanelConsulta = new javax.swing.JPanel();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableChamado = new javax.swing.JTable();
        jPanelAcoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelId11 = new javax.swing.JLabel();
        tfAbaFechaIdChamado2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfAbaFechaNomeCliente2 = new javax.swing.JTextField();
        jLabelId12 = new javax.swing.JLabel();
        tfAbaFechaIdCliente2 = new javax.swing.JTextField();
        jLabelId13 = new javax.swing.JLabel();
        tfAbaFechaIdEquipamento2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfAbaFechaFabricanteEquipamento2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfAbaFechaModeloEquipamento2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfAbaFechaSerialEquipamento2 = new javax.swing.JTextField();
        jLabelId14 = new javax.swing.JLabel();
        tfAbaFechaDataAbertura2 = new javax.swing.JTextField();
        jLabelId15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        taAbaFechaDefeitoRelatado2 = new javax.swing.JTextArea();
        jLabelId16 = new javax.swing.JLabel();
        tfAbaFechaDataAbertura3 = new javax.swing.JTextField();
        jLabelId17 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        taAbaFechaDefeitoRelatado3 = new javax.swing.JTextArea();
        jLabelId18 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        taAbaFechaDefeitoRelatado4 = new javax.swing.JTextArea();
        jPanelAbertura = new javax.swing.JPanel();
        jPanelDadosChamado = new javax.swing.JPanel();
        jLabelFabricante = new javax.swing.JLabel();
        jLabelDono = new javax.swing.JLabel();
        cbAbaAbreCliente = new javax.swing.JComboBox<>();
        cbAbaAbreEquipamentos = new javax.swing.JComboBox<>();
        jLabelId10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taAbaAbreDefeitoRelatado = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabelId8 = new javax.swing.JLabel();
        tfAbaAbreIdEquipamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfAbaAbreFabricanteEquipamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfAbaAbreModeloEquipamento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfAbaAbreSerialEquipamento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfAbaAbreTelaEquipamento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfAbaAbreRamEquipamento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfAbaAbreHdEquipamento = new javax.swing.JTextField();
        jPanelBotoes = new javax.swing.JPanel();
        btAbaAbreLimparCampos = new javax.swing.JButton();
        btAbaAbreAbrirChamado = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btAbaAbreCancelar = new javax.swing.JButton();
        jButtonFecharJanela = new javax.swing.JButton();
        jPanelFechamento = new javax.swing.JPanel();
        jPanelDadosChamado1 = new javax.swing.JPanel();
        jLabelModelo2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taAbaFechamentoDefeitoConstatado = new javax.swing.JTextArea();
        jLabelModelo3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taAbaFechamentoSolucao = new javax.swing.JTextArea();
        jPanelBotoes1 = new javax.swing.JPanel();
        jButtonLimpar1 = new javax.swing.JButton();
        btFechaChamado = new javax.swing.JButton();
        btAbaFechaListarChamados = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        btAbaEncerramentoFechaJanela = new javax.swing.JButton();
        btAbaFechaAtChamado = new javax.swing.JButton();
        btAbaFechaCancelaAt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelId1 = new javax.swing.JLabel();
        tfAbaFechaIdChamado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfAbaFechaNomeCliente = new javax.swing.JTextField();
        jLabelId2 = new javax.swing.JLabel();
        tfAbaFechaIdCliente = new javax.swing.JTextField();
        jLabelId3 = new javax.swing.JLabel();
        tfAbaFechaIdEquipamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfAbaFechaFabricanteEquipamento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfAbaFechaModeloEquipamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfAbaFechaSerialEquipamento = new javax.swing.JTextField();
        jLabelId4 = new javax.swing.JLabel();
        tfAbaFechaDataAbertura = new javax.swing.JTextField();
        jLabelId5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAbaFechaDefeitoRelatado = new javax.swing.JTextArea();
        jLabelDono1 = new javax.swing.JLabel();
        cbChamadosAbertos = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(787, 412));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Chamados"));

        jTableChamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HP", "Garantia pelo Fabricante"}
            },
            new String [] {
                "Cód", "Fabricante", "Obs"
            }
        ));
        jTableChamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableChamadoMouseClicked(evt);
            }
        });
        jTableChamado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableChamadoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableChamado);

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 142, Short.MAX_VALUE))
        );

        jPanelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcoesLayout = new javax.swing.GroupLayout(jPanelAcoes);
        jPanelAcoes.setLayout(jPanelAcoesLayout);
        jPanelAcoesLayout.setHorizontalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAcoesLayout.setVerticalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do chamado"));

        jLabelId11.setText("ID do Chamado");

        tfAbaFechaIdChamado2.setEditable(false);

        jLabel10.setText("Nome do Cliente:");

        tfAbaFechaNomeCliente2.setEnabled(false);

        jLabelId12.setText("ID do Cliente");

        tfAbaFechaIdCliente2.setEditable(false);

        jLabelId13.setText("ID do Equipamento");

        tfAbaFechaIdEquipamento2.setEditable(false);

        jLabel11.setText("Fabricante");

        tfAbaFechaFabricanteEquipamento2.setEnabled(false);

        jLabel12.setText("Modelo:");

        tfAbaFechaModeloEquipamento2.setEnabled(false);

        jLabel13.setText("Serial:");

        tfAbaFechaSerialEquipamento2.setEnabled(false);

        jLabelId14.setText("Abertura");

        tfAbaFechaDataAbertura2.setEditable(false);

        jLabelId15.setText("Defeito Relatado");

        taAbaFechaDefeitoRelatado2.setBackground(new java.awt.Color(240, 240, 240));
        taAbaFechaDefeitoRelatado2.setColumns(20);
        taAbaFechaDefeitoRelatado2.setLineWrap(true);
        taAbaFechaDefeitoRelatado2.setRows(5);
        taAbaFechaDefeitoRelatado2.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechaDefeitoRelatado2.setEnabled(false);
        jScrollPane7.setViewportView(taAbaFechaDefeitoRelatado2);

        jLabelId16.setText("Encerramento");

        tfAbaFechaDataAbertura3.setEditable(false);

        jLabelId17.setText("Defeito Constatado:");

        taAbaFechaDefeitoRelatado3.setBackground(new java.awt.Color(240, 240, 240));
        taAbaFechaDefeitoRelatado3.setColumns(20);
        taAbaFechaDefeitoRelatado3.setLineWrap(true);
        taAbaFechaDefeitoRelatado3.setRows(5);
        taAbaFechaDefeitoRelatado3.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechaDefeitoRelatado3.setEnabled(false);
        jScrollPane8.setViewportView(taAbaFechaDefeitoRelatado3);

        jLabelId18.setText("Solução");

        taAbaFechaDefeitoRelatado4.setBackground(new java.awt.Color(240, 240, 240));
        taAbaFechaDefeitoRelatado4.setColumns(20);
        taAbaFechaDefeitoRelatado4.setLineWrap(true);
        taAbaFechaDefeitoRelatado4.setRows(5);
        taAbaFechaDefeitoRelatado4.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechaDefeitoRelatado4.setEnabled(false);
        jScrollPane9.setViewportView(taAbaFechaDefeitoRelatado4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelId11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaIdChamado2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelId12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaIdCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaNomeCliente2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelId13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaIdEquipamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaFabricanteEquipamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaModeloEquipamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaSerialEquipamento2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelId14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfAbaFechaDataAbertura2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelId16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfAbaFechaDataAbertura3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelId17)
                                    .addComponent(jLabelId15))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelId18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane8))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId11)
                    .addComponent(tfAbaFechaIdChamado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfAbaFechaNomeCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId12)
                    .addComponent(tfAbaFechaIdCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfAbaFechaFabricanteEquipamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId13)
                    .addComponent(tfAbaFechaIdEquipamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfAbaFechaModeloEquipamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfAbaFechaSerialEquipamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelId14)
                        .addComponent(tfAbaFechaDataAbertura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelId15))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelId16)
                        .addComponent(tfAbaFechaDataAbertura3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelId17))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId18)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelTabela.getAccessibleContext().setAccessibleName("Dados Pessoais");

        jTabbedPaneChamados.addTab("Consulta", jPanelConsulta);

        jPanelDadosChamado.setBorder(javax.swing.BorderFactory.createTitledBorder("Abertura de Chamado"));
        jPanelDadosChamado.setPreferredSize(new java.awt.Dimension(787, 412));

        jLabelFabricante.setText("Equipamento:");

        jLabelDono.setText("Cliente:");

        cbAbaAbreCliente.setEnabled(false);
        cbAbaAbreCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAbaAbreClienteItemStateChanged(evt);
            }
        });

        cbAbaAbreEquipamentos.setEnabled(false);
        cbAbaAbreEquipamentos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAbaAbreEquipamentosItemStateChanged(evt);
            }
        });

        jLabelId10.setText("Defeito Relatado");

        taAbaAbreDefeitoRelatado.setColumns(20);
        taAbaAbreDefeitoRelatado.setLineWrap(true);
        taAbaAbreDefeitoRelatado.setRows(5);
        taAbaAbreDefeitoRelatado.setToolTipText("Descreve o problema do Equipamento");
        taAbaAbreDefeitoRelatado.setEnabled(false);
        jScrollPane6.setViewportView(taAbaAbreDefeitoRelatado);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do Equipamento"));

        jLabelId8.setText("ID do Equipamento");

        tfAbaAbreIdEquipamento.setEditable(false);

        jLabel7.setText("Fabricante");

        tfAbaAbreFabricanteEquipamento.setEnabled(false);

        jLabel8.setText("Modelo:");

        tfAbaAbreModeloEquipamento.setEnabled(false);

        jLabel9.setText("Serial:");

        tfAbaAbreSerialEquipamento.setEnabled(false);

        jLabel14.setText("Tamanho da Tela:");

        tfAbaAbreTelaEquipamento.setEnabled(false);

        jLabel15.setText("Memória RAM:");

        tfAbaAbreRamEquipamento.setEnabled(false);

        jLabel16.setText("HD:");

        tfAbaAbreHdEquipamento.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelId8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaAbreIdEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaAbreFabricanteEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaAbreModeloEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaAbreSerialEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaAbreTelaEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaAbreRamEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaAbreHdEquipamento)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId8)
                    .addComponent(tfAbaAbreIdEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfAbaAbreFabricanteEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfAbaAbreModeloEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfAbaAbreSerialEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfAbaAbreTelaEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfAbaAbreRamEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfAbaAbreHdEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelDadosChamadoLayout = new javax.swing.GroupLayout(jPanelDadosChamado);
        jPanelDadosChamado.setLayout(jPanelDadosChamadoLayout);
        jPanelDadosChamadoLayout.setHorizontalGroup(
            jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                        .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFabricante)
                            .addComponent(jLabelDono))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAbaAbreEquipamentos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbAbaAbreCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                        .addComponent(jLabelId10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelDadosChamadoLayout.setVerticalGroup(
            jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDono)
                    .addComponent(cbAbaAbreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabricante)
                    .addComponent(cbAbaAbreEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addGroup(jPanelDadosChamadoLayout.createSequentialGroup()
                        .addComponent(jLabelId10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        btAbaAbreLimparCampos.setText("Limpar Campos");
        btAbaAbreLimparCampos.setEnabled(false);
        btAbaAbreLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaAbreLimparCamposActionPerformed(evt);
            }
        });

        btAbaAbreAbrirChamado.setText("Abrir Chamado");
        btAbaAbreAbrirChamado.setEnabled(false);
        btAbaAbreAbrirChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaAbreAbrirChamadoActionPerformed(evt);
            }
        });

        btNovo.setText("Novo Chamado");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAbaAbreCancelar.setText("Cancelar");
        btAbaAbreCancelar.setEnabled(false);
        btAbaAbreCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaAbreCancelarActionPerformed(evt);
            }
        });

        jButtonFecharJanela.setText("Fechar");
        jButtonFecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharJanelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAbaAbreLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbaAbreAbrirChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbaAbreCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFecharJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbaAbreAbrirChamado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbaAbreCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbaAbreLimparCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharJanela)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jPanelAberturaLayout = new javax.swing.GroupLayout(jPanelAbertura);
        jPanelAbertura.setLayout(jPanelAberturaLayout);
        jPanelAberturaLayout.setHorizontalGroup(
            jPanelAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosChamado, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanelAberturaLayout.setVerticalGroup(
            jPanelAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDadosChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPaneChamados.addTab("Abertura de Chamados", jPanelAbertura);

        jPanelDadosChamado1.setBorder(javax.swing.BorderFactory.createTitledBorder("Encerramento"));
        jPanelDadosChamado1.setPreferredSize(new java.awt.Dimension(787, 412));

        jLabelModelo2.setText("Defeito Constatado");

        taAbaFechamentoDefeitoConstatado.setColumns(20);
        taAbaFechamentoDefeitoConstatado.setLineWrap(true);
        taAbaFechamentoDefeitoConstatado.setRows(5);
        taAbaFechamentoDefeitoConstatado.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechamentoDefeitoConstatado.setEnabled(false);
        jScrollPane4.setViewportView(taAbaFechamentoDefeitoConstatado);

        jLabelModelo3.setText("Solução");

        taAbaFechamentoSolucao.setColumns(20);
        taAbaFechamentoSolucao.setLineWrap(true);
        taAbaFechamentoSolucao.setRows(5);
        taAbaFechamentoSolucao.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechamentoSolucao.setEnabled(false);
        jScrollPane5.setViewportView(taAbaFechamentoSolucao);

        javax.swing.GroupLayout jPanelDadosChamado1Layout = new javax.swing.GroupLayout(jPanelDadosChamado1);
        jPanelDadosChamado1.setLayout(jPanelDadosChamado1Layout);
        jPanelDadosChamado1Layout.setHorizontalGroup(
            jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosChamado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelo2)
                    .addComponent(jLabelModelo3))
                .addGap(24, 24, 24)
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanelDadosChamado1Layout.setVerticalGroup(
            jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosChamado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelo2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelo3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelBotoes1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButtonLimpar1.setText("Limpar Campos");
        jButtonLimpar1.setEnabled(false);
        jButtonLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpar1ActionPerformed(evt);
            }
        });

        btFechaChamado.setText("Fechar Chamado");
        btFechaChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechaChamadoActionPerformed(evt);
            }
        });

        btAbaFechaListarChamados.setText("Listar Chamados");
        btAbaFechaListarChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaFechaListarChamadosActionPerformed(evt);
            }
        });

        jButtonCancelar1.setText("Cancelar");
        jButtonCancelar1.setEnabled(false);
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });

        btAbaEncerramentoFechaJanela.setText("Fechar");
        btAbaEncerramentoFechaJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaEncerramentoFechaJanelaActionPerformed(evt);
            }
        });

        btAbaFechaAtChamado.setText("Iniciar Atendimento");
        btAbaFechaAtChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaFechaAtChamadoActionPerformed(evt);
            }
        });

        btAbaFechaCancelaAt.setText("Cancelar Atendimento");
        btAbaFechaCancelaAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaFechaCancelaAtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoes1Layout = new javax.swing.GroupLayout(jPanelBotoes1);
        jPanelBotoes1.setLayout(jPanelBotoes1Layout);
        jPanelBotoes1Layout.setHorizontalGroup(
            jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoes1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAbaFechaAtChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbaFechaCancelaAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbaFechaListarChamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFechaChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbaEncerramentoFechaJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBotoes1Layout.setVerticalGroup(
            jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAbaFechaListarChamados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbaFechaAtChamado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbaFechaCancelaAt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechaChamado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbaEncerramentoFechaJanela)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do chamado"));

        jLabelId1.setText("ID do Chamado");

        tfAbaFechaIdChamado.setEditable(false);

        jLabel2.setText("Nome do Cliente:");

        tfAbaFechaNomeCliente.setEnabled(false);

        jLabelId2.setText("ID do Cliente");

        tfAbaFechaIdCliente.setEditable(false);

        jLabelId3.setText("ID do Equipamento");

        tfAbaFechaIdEquipamento.setEditable(false);

        jLabel3.setText("Fabricante");

        tfAbaFechaFabricanteEquipamento.setEnabled(false);

        jLabel4.setText("Modelo:");

        tfAbaFechaModeloEquipamento.setEnabled(false);

        jLabel5.setText("Serial:");

        tfAbaFechaSerialEquipamento.setEnabled(false);

        jLabelId4.setText("Data de Abertura");

        tfAbaFechaDataAbertura.setEditable(false);

        jLabelId5.setText("Defeito Relatado");

        taAbaFechaDefeitoRelatado.setBackground(new java.awt.Color(240, 240, 240));
        taAbaFechaDefeitoRelatado.setColumns(20);
        taAbaFechaDefeitoRelatado.setLineWrap(true);
        taAbaFechaDefeitoRelatado.setRows(5);
        taAbaFechaDefeitoRelatado.setToolTipText("Descreve o problema do Equipamento");
        taAbaFechaDefeitoRelatado.setEnabled(false);
        jScrollPane3.setViewportView(taAbaFechaDefeitoRelatado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelId1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaIdChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelId2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAbaFechaNomeCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelId4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAbaFechaDataAbertura))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelId3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAbaFechaIdEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfAbaFechaFabricanteEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAbaFechaModeloEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAbaFechaSerialEquipamento))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelId5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId1)
                    .addComponent(tfAbaFechaIdChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfAbaFechaNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId2)
                    .addComponent(tfAbaFechaIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAbaFechaFabricanteEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId3)
                    .addComponent(tfAbaFechaIdEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfAbaFechaModeloEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfAbaFechaSerialEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId4)
                            .addComponent(tfAbaFechaDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId5))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelDono1.setText("Chamados");

        cbChamadosAbertos.setEnabled(false);
        cbChamadosAbertos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbChamadosAbertosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelFechamentoLayout = new javax.swing.GroupLayout(jPanelFechamento);
        jPanelFechamento.setLayout(jPanelFechamentoLayout);
        jPanelFechamentoLayout.setHorizontalGroup(
            jPanelFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFechamentoLayout.createSequentialGroup()
                .addGroup(jPanelFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFechamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDono1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbChamadosAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFechamentoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanelDadosChamado1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFechamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanelFechamentoLayout.setVerticalGroup(
            jPanelFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechamentoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFechamentoLayout.createSequentialGroup()
                        .addGroup(jPanelFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDono1)
                            .addComponent(cbChamadosAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDadosChamado1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jTabbedPaneChamados.addTab("Fechamento de Chamados", jPanelFechamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAbaAbreLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaAbreLimparCamposActionPerformed
        // Limpa os campos
        limparCampos();
    }//GEN-LAST:event_btAbaAbreLimparCamposActionPerformed

    private void btAbaAbreAbrirChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaAbreAbrirChamadoActionPerformed
        if (!taAbaAbreDefeitoRelatado.getText().equals("")) {
            Notebook notebook = NotebookJpaDao.getInstance().getById(Integer.parseInt(tfAbaAbreIdEquipamento.getText()));
            String defeitoRelatado = taAbaAbreDefeitoRelatado.getText();
            Chamado chamado = new Chamado(notebook, defeitoRelatado);
            if (ChamadoJpaDao.getInstance().create(chamado)) {
                JOptionPane.showMessageDialog(this, "Chamado aberto com sucesso");
                listarChamadosNaTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao abrir chamado");
            }
            
        } else {
                JOptionPane.showMessageDialog(this, "Descreva o problema do equipamento.");
        }
    }//GEN-LAST:event_btAbaAbreAbrirChamadoActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        habilitaCamposAbaAbrir(true);
        habilitaBotoesAbaAbrir(true);
        populaClientesAbaAbreChamados();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAbaAbreCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaAbreCancelarActionPerformed
        // TODO add your handling code here:
        habilitaBotoesAbaAbrir(false);
        habilitaCamposAbaAbrir(false);
        cbAbaAbreCliente.setSelectedIndex(-1);
        cbAbaAbreEquipamentos.setSelectedIndex(-1);
        taAbaAbreDefeitoRelatado.setText("");
    }//GEN-LAST:event_btAbaAbreCancelarActionPerformed

    private void jTableChamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableChamadoMouseClicked
        // TODO add your handling code here:
        populaCamposByJTable();
    }//GEN-LAST:event_jTableChamadoMouseClicked

    private void jButtonFecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharJanelaActionPerformed

    private void jTableChamadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableChamadoKeyPressed
        // TODO add your handling code here:
        populaCamposByJTable();
    }//GEN-LAST:event_jTableChamadoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        listarChamadosNaTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpar1ActionPerformed

    private void btFechaChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechaChamadoActionPerformed
        // TODO add your handling code here:
        if (cbChamadosAbertos.getSelectedIndex() != -1) {
            Chamado chamadoAt = ChamadoJpaDao.getInstance().getById(Integer.parseInt(tfAbaFechaIdChamado.getText()));
            chamadoAt.setDefeitoConstatado(taAbaFechamentoDefeitoConstatado.getText());
            chamadoAt.setSolucao(taAbaFechamentoSolucao.getText());
            chamadoAt.setDataFechamento(Calendar.getInstance().getTime());
            chamadoAt.setStatus(Chamado.FECHADO);

            if (ChamadoJpaDao.getInstance().update(chamadoAt)) {
                JOptionPane.showMessageDialog(null, "Chamado fechado com sucesso");
                cbChamadosAbertos.removeAllItems();
                getChamadosAbertos();
                tfAbaFechaIdChamado.setText("");
                taAbaFechaDefeitoRelatado.setText("");
                taAbaFechamentoDefeitoConstatado.setText("");
                taAbaFechamentoSolucao.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar fechar chamado");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um chamado aberto para fechar");
        }
    }//GEN-LAST:event_btFechaChamadoActionPerformed

    private void btAbaFechaListarChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaFechaListarChamadosActionPerformed
        listarChamados();
    }//GEN-LAST:event_btAbaFechaListarChamadosActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void btAbaEncerramentoFechaJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaEncerramentoFechaJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAbaEncerramentoFechaJanelaActionPerformed

    private void cbChamadosAbertosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChamadosAbertosItemStateChanged
        // TODO add your handling code here:
        //Montar Lógica de preencher as coisas...
        if (cbChamadosAbertos.getSelectedIndex() != -1) {
            Chamado chAt = (Chamado) cbChamadosAbertos.getSelectedItem();
            tfAbaFechaIdChamado.setText("" + chAt.getId());
            tfAbaFechaIdCliente.setText("" + chAt.getNotebook().getDono().getId());
            tfAbaFechaNomeCliente.setText(chAt.getNotebook().getDono().getNome());
            tfAbaFechaIdEquipamento.setText("" + chAt.getNotebook().getId());
            tfAbaFechaFabricanteEquipamento.setText("" + chAt.getNotebook().getFabricante());
            tfAbaFechaModeloEquipamento.setText(chAt.getNotebook().getModelo());
            tfAbaFechaSerialEquipamento.setText(chAt.getNotebook().getSerial());
            tfAbaFechaDataAbertura.setText("" + chAt.getDataAbertura());
            taAbaFechaDefeitoRelatado.setText(chAt.getDefeitoRelatado());
        }
    }//GEN-LAST:event_cbChamadosAbertosItemStateChanged

    private void btAbaFechaAtChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaFechaAtChamadoActionPerformed
        // TODO add your handling code here:
        if (cbChamadosAbertos.getSelectedIndex() != -1) {
            Chamado chtAux = (Chamado) cbChamadosAbertos.getSelectedItem();
            chEmAt = ChamadoJpaDao.getInstance().getById(chtAux.getId());

            chEmAt.setStatus(Chamado.AT);
            if (ChamadoJpaDao.getInstance().update(chEmAt)) {
                cbChamadosAbertos.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Iniciado atendimento ao chamado " + chEmAt.getId() + " com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao iniciar o atendimento ao " + chEmAt.getId() + " .");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum chamato selecionado para iniciar atendimento");
        }
    }//GEN-LAST:event_btAbaFechaAtChamadoActionPerformed

    private void btAbaFechaCancelaAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaFechaCancelaAtActionPerformed
        // TODO add your handling code here:
        Chamado pararChamado = ChamadoJpaDao.getInstance().getById(chEmAt.getId());
        pararChamado.setStatus(Chamado.ABERTO);
        if (ChamadoJpaDao.getInstance().update(pararChamado)) {
            cbChamadosAbertos.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Cancelado atendimento ao chamado " + pararChamado.getId() + " com sucesso.");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cancelar o atendimento ao " + pararChamado.getId() + " .");
        }
    }//GEN-LAST:event_btAbaFechaCancelaAtActionPerformed

    private void cbAbaAbreEquipamentosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAbaAbreEquipamentosItemStateChanged
        // TODO add your handling code here:
        if (cbAbaAbreEquipamentos.getSelectedIndex() != -1 && cbAbaAbreCliente.getSelectedIndex() != -1) {
            Notebook noteExemplo = (Notebook) cbAbaAbreEquipamentos.getSelectedItem();
            Notebook noteBanco = NotebookJpaDao.getInstance().getById(noteExemplo.getId());
            
            tfAbaAbreIdEquipamento.setText(""+noteBanco.getId());
            tfAbaAbreFabricanteEquipamento.setText(""+noteBanco.getFabricante());
            tfAbaAbreModeloEquipamento.setText(noteBanco.getModelo());
            tfAbaAbreSerialEquipamento.setText(noteBanco.getSerial());
            tfAbaAbreTelaEquipamento.setText(noteBanco.getTamanhoTela());
            tfAbaAbreRamEquipamento.setText(noteBanco.getRam());
            tfAbaAbreHdEquipamento.setText(noteBanco.getHd());
            
        }
    }//GEN-LAST:event_cbAbaAbreEquipamentosItemStateChanged

    private void cbAbaAbreClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAbaAbreClienteItemStateChanged
        // TODO add your handling code here:
        popularEquipamentosDoClienteSelecionado();
    }//GEN-LAST:event_cbAbaAbreClienteItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbaAbreAbrirChamado;
    private javax.swing.JButton btAbaAbreCancelar;
    private javax.swing.JButton btAbaAbreLimparCampos;
    private javax.swing.JButton btAbaEncerramentoFechaJanela;
    private javax.swing.JButton btAbaFechaAtChamado;
    private javax.swing.JButton btAbaFechaCancelaAt;
    private javax.swing.JButton btAbaFechaListarChamados;
    private javax.swing.JButton btFechaChamado;
    private javax.swing.JButton btNovo;
    private javax.swing.JComboBox<ClientePf> cbAbaAbreCliente;
    private javax.swing.JComboBox<Notebook> cbAbaAbreEquipamentos;
    private javax.swing.JComboBox<Chamado> cbChamadosAbertos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonFecharJanela;
    private javax.swing.JButton jButtonLimpar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDono;
    private javax.swing.JLabel jLabelDono1;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelId10;
    private javax.swing.JLabel jLabelId11;
    private javax.swing.JLabel jLabelId12;
    private javax.swing.JLabel jLabelId13;
    private javax.swing.JLabel jLabelId14;
    private javax.swing.JLabel jLabelId15;
    private javax.swing.JLabel jLabelId16;
    private javax.swing.JLabel jLabelId17;
    private javax.swing.JLabel jLabelId18;
    private javax.swing.JLabel jLabelId2;
    private javax.swing.JLabel jLabelId3;
    private javax.swing.JLabel jLabelId4;
    private javax.swing.JLabel jLabelId5;
    private javax.swing.JLabel jLabelId8;
    private javax.swing.JLabel jLabelModelo2;
    private javax.swing.JLabel jLabelModelo3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAbertura;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelBotoes1;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelDadosChamado;
    private javax.swing.JPanel jPanelDadosChamado1;
    private javax.swing.JPanel jPanelFechamento;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPaneChamados;
    private javax.swing.JTable jTableChamado;
    private javax.swing.JTextArea taAbaAbreDefeitoRelatado;
    private javax.swing.JTextArea taAbaFechaDefeitoRelatado;
    private javax.swing.JTextArea taAbaFechaDefeitoRelatado2;
    private javax.swing.JTextArea taAbaFechaDefeitoRelatado3;
    private javax.swing.JTextArea taAbaFechaDefeitoRelatado4;
    private javax.swing.JTextArea taAbaFechamentoDefeitoConstatado;
    private javax.swing.JTextArea taAbaFechamentoSolucao;
    private javax.swing.JTextField tfAbaAbreFabricanteEquipamento;
    private javax.swing.JTextField tfAbaAbreHdEquipamento;
    private javax.swing.JTextField tfAbaAbreIdEquipamento;
    private javax.swing.JTextField tfAbaAbreModeloEquipamento;
    private javax.swing.JTextField tfAbaAbreRamEquipamento;
    private javax.swing.JTextField tfAbaAbreSerialEquipamento;
    private javax.swing.JTextField tfAbaAbreTelaEquipamento;
    private javax.swing.JTextField tfAbaFechaDataAbertura;
    private javax.swing.JTextField tfAbaFechaDataAbertura2;
    private javax.swing.JTextField tfAbaFechaDataAbertura3;
    private javax.swing.JTextField tfAbaFechaFabricanteEquipamento;
    private javax.swing.JTextField tfAbaFechaFabricanteEquipamento2;
    private javax.swing.JTextField tfAbaFechaIdChamado;
    private javax.swing.JTextField tfAbaFechaIdChamado2;
    private javax.swing.JTextField tfAbaFechaIdCliente;
    private javax.swing.JTextField tfAbaFechaIdCliente2;
    private javax.swing.JTextField tfAbaFechaIdEquipamento;
    private javax.swing.JTextField tfAbaFechaIdEquipamento2;
    private javax.swing.JTextField tfAbaFechaModeloEquipamento;
    private javax.swing.JTextField tfAbaFechaModeloEquipamento2;
    private javax.swing.JTextField tfAbaFechaNomeCliente;
    private javax.swing.JTextField tfAbaFechaNomeCliente2;
    private javax.swing.JTextField tfAbaFechaSerialEquipamento;
    private javax.swing.JTextField tfAbaFechaSerialEquipamento2;
    // End of variables declaration//GEN-END:variables

    private void populaClientesAbaAbreChamados() {
        cbAbaAbreCliente.removeAllItems();
        List<ClientePf> listaClientesPf = ClientePfJpaDao.getInstance().readAll();
        for (ClientePf clientePf : listaClientesPf) {
            cbAbaAbreCliente.addItem(clientePf);
        }
        cbAbaAbreCliente.setSelectedIndex(-1);
    }

    private void popularEquipamentosDoClienteSelecionado() {
        ClientePf clientePf = (ClientePf) cbAbaAbreCliente.getSelectedItem();
        cbAbaAbreEquipamentos.removeAllItems();
        List<Notebook> listaEquipamentosCliente = NotebookJpaDao.getInstance().getAllByIdDono(clientePf.getId());
        for (Notebook notebookCliente : listaEquipamentosCliente) {
            cbAbaAbreEquipamentos.addItem(notebookCliente);
        }
        cbAbaAbreEquipamentos.setSelectedIndex(-1);
    }

    public void listarChamadosNaTabela() {
        limpaTabela();
        List<Chamado> listaChamado = ChamadoJpaDao.getInstance().readAll();
        listaChamado.forEach((chamado) -> {
            tableModel.addRow(chamado);
        });
        //jTableChamado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableChamado.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTableChamado);
        tca.adjustColumns();
    }

    public void limpaTabela() {
        tableModel.limpaTabela();
    }

    public void limparCampos() {
//        tfId.setText("");
//        taDefeitoRelatado.setText("");
    }

    public boolean CamposEmBranco() {
//        int erros = 0;
//        if (taDefeitoRelatado.getText().equals("")) {
//            erros++;
//        }
//        if (erros == 0) {
//            return false;
//        } else {
//            return true;
//        }
        return false;
    }

    private void habilitaCamposAbaAbrir(boolean estado) {
        JComboBox[] listaComboBoxes = {cbAbaAbreCliente, cbAbaAbreEquipamentos};
        for (JComboBox comboBox : listaComboBoxes) {
            comboBox.setEnabled(estado);
        }
        taAbaAbreDefeitoRelatado.setEnabled(estado);
    }

    private void habilitaBotoesAbaAbrir(boolean estado) {
        btAbaAbreCancelar.setEnabled(estado);
        btAbaAbreLimparCampos.setEnabled(estado);
        btAbaAbreAbrirChamado.setEnabled(estado);
    }

    private void populaCamposByJTable() {
        if (jTableChamado.getSelectedRow() != -1) {

//            tfId.setText(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 0).toString());
//            cbDono.setSelectedIndex(Integer.parseInt(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 1).toString()) - 1);
//            EquipamentosTipo tipoEquipamento = (EquipamentosTipo) jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 4);
//            jComboBoxTipoEquipamento.setSelectedIndex(tipoEquipamento.getId() - 1);
//            Fabricante fabricante = (Fabricante) jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 5);
//            cbEquipamento.setSelectedIndex(fabricante.getId() - 1);
//            tfModelo.setText(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 6).toString());
//            tfSerial.setText(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 7).toString());
//            jComboBoxTela.setSelectedItem(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 8));
//            jComboBoxRam.setSelectedItem(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 9));
//            jComboBoxHd.setSelectedItem(jTableChamado.getValueAt(jTableChamado.getSelectedRow(), 10));
        }
    }

    private void listarChamados() {
        getChamadosAbertos();
        cbChamadosAbertos.setEnabled(true);
        taAbaFechaDefeitoRelatado.enable(true);
        taAbaFechamentoDefeitoConstatado.enable(true);
        taAbaFechamentoSolucao.enable(true);
        btFechaChamado.setEnabled(true);
    }

    private void getChamadosAbertos() {
        cbChamadosAbertos.removeAllItems();
        List<Chamado> listaChamadoAbertos = ChamadoJpaDao.getInstance().readAll();
        for (Chamado chamado : listaChamadoAbertos) {
            if (chamado.getStatus().equals(Chamado.ABERTO)) {
                cbChamadosAbertos.addItem(chamado);

            }
        }
    }

}
