/*
 * The MIT License
 *
 * Copyright 2019 Rodrigo Ferreira Rodrigues <https://github.com/rfrodriguespe>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.rftech.view;

import br.com.rftech.Dao.ClientePfJpaDao;
import br.com.rftech.Dao.ClientePfJdbcDao;
import br.com.rftech.bean.ClientePf;
import br.com.rftech.bean.ClientePfTableModel;
import br.com.rftech.bean.Endereco;
import br.com.rftech.bean.TableColumnAdjuster;
import br.com.rftech.testes.TesteCEP;
import br.com.rftech.util.ValidaCampos;
import com.github.gilbertotorrezan.viacep.se.ViaCEPClient;
import com.github.gilbertotorrezan.viacep.shared.ViaCEPEndereco;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo Ferreira Rodrigues <https://github.com/rfrodriguespe>
 */
public class ClientePfView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientesPFView
     */
    public ClientePfView() {
        initComponents();
        jTableClientePf.setModel(tableModel);
        habilitaCampos(false);
    }

    //Instancia minha jTable com base no modelo de Tabela definido no pacote MODEL
    ClientePfTableModel tableModel = new ClientePfTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupPersistencia = new javax.swing.ButtonGroup();
        jPanelDadosClientePf = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        ftfCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftfTelefone = new javax.swing.JFormattedTextField();
        tfEmail = new javax.swing.JTextField();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientePf = new javax.swing.JTable();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVerificaPendencias = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFecharJanela = new javax.swing.JButton();
        jPanelTipoPersistencia = new javax.swing.JPanel();
        rbJpa = new javax.swing.JRadioButton();
        rdJdbc = new javax.swing.JRadioButton();
        btListar = new javax.swing.JButton();
        jPanelEndereco = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ftfCep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonPesquisaCep = new javax.swing.JButton();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jPanelAcoes = new javax.swing.JPanel();
        tfConsulta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbTipoPesquisa = new javax.swing.JComboBox<>();
        btAbaConsultaPesquisar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        labelQtdeClientePf = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(787, 412));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelDadosClientePf.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        jPanelDadosClientePf.setPreferredSize(new java.awt.Dimension(787, 412));

        tfNome.setEnabled(false);
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfId.setEditable(false);

        jLabelCPF.setText("CPF:");

        jLabelNome.setText("Nome:");

        jLabelId.setText("ID:");

        try {
            ftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCpf.setEnabled(false);
        ftfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfCpfFocusLost(evt);
            }
        });

        jLabel4.setText("Telefone:");

        jLabel5.setText("E-mail:");

        try {
            ftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfTelefone.setEnabled(false);

        tfEmail.setEnabled(false);

        javax.swing.GroupLayout jPanelDadosClientePfLayout = new javax.swing.GroupLayout(jPanelDadosClientePf);
        jPanelDadosClientePf.setLayout(jPanelDadosClientePfLayout);
        jPanelDadosClientePfLayout.setHorizontalGroup(
            jPanelDadosClientePfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosClientePfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosClientePfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosClientePfLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome)
                        .addGap(10, 10, 10))
                    .addGroup(jPanelDadosClientePfLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail)
                        .addContainerGap())))
        );
        jPanelDadosClientePfLayout.setVerticalGroup(
            jPanelDadosClientePfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosClientePfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosClientePfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF)
                    .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosClientePfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Clientes Pessoa Física"));

        jTableClientePf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HP", "Garantia pelo Fabricante"}
            },
            new String [] {
                "Cód", "Fabricante", "Obs"
            }
        ));
        jTableClientePf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientePfMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableClientePfMouseReleased(evt);
            }
        });
        jTableClientePf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableClientePfKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientePf);

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar Campos");
        jButtonLimpar.setEnabled(false);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVerificaPendencias.setText("Verifica Pendências");
        jButtonVerificaPendencias.setEnabled(false);
        jButtonVerificaPendencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificaPendenciasActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFecharJanela.setText("Fechar");
        jButtonFecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharJanelaActionPerformed(evt);
            }
        });

        jPanelTipoPersistencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Persistência"));

        btGroupPersistencia.add(rbJpa);
        rbJpa.setSelected(true);
        rbJpa.setText("JPA");

        btGroupPersistencia.add(rdJdbc);
        rdJdbc.setText("JDBC");

        javax.swing.GroupLayout jPanelTipoPersistenciaLayout = new javax.swing.GroupLayout(jPanelTipoPersistencia);
        jPanelTipoPersistencia.setLayout(jPanelTipoPersistenciaLayout);
        jPanelTipoPersistenciaLayout.setHorizontalGroup(
            jPanelTipoPersistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoPersistenciaLayout.createSequentialGroup()
                .addGroup(jPanelTipoPersistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbJpa)
                    .addComponent(rdJdbc))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanelTipoPersistenciaLayout.setVerticalGroup(
            jPanelTipoPersistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoPersistenciaLayout.createSequentialGroup()
                .addComponent(rbJpa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdJdbc))
        );

        btListar.setText("Listar Todos");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotoesLayout.createSequentialGroup()
                        .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTipoPersistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBotoesLayout.createSequentialGroup()
                        .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonVerificaPendencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFecharJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotoesLayout.createSequentialGroup()
                        .addComponent(btListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar))
                    .addComponent(jPanelTipoPersistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerificaPendencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonFecharJanela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel6.setText("CEP:");

        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCep.setEnabled(false);

        jLabel7.setText("Logradouro");

        tfLogradouro.setEnabled(false);

        jLabel8.setText("Número:");

        tfNumero.setEnabled(false);

        tfComplemento.setEnabled(false);

        jLabel9.setText("Complemento");

        jLabel10.setText("Bairro");

        tfBairro.setEnabled(false);

        jLabel11.setText("Cidade");

        tfCidade.setEnabled(false);

        jLabel12.setText("UF");

        jButtonPesquisaCep.setText("Pesquisa CEP");
        jButtonPesquisaCep.setEnabled(false);
        jButtonPesquisaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaCepActionPerformed(evt);
            }
        });

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxEstado.setToolTipText("");
        jComboBoxEstado.setEnabled(false);

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLogradouro))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisaCep)
                    .addComponent(jLabel7)
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jLabel13.setText("Pesquisar Cliente");

        cbTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesquisar por", "Id Cliente", "Nome" }));
        cbTipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPesquisaActionPerformed(evt);
            }
        });

        btAbaConsultaPesquisar.setText("Pesquisar");
        btAbaConsultaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbaConsultaPesquisarActionPerformed(evt);
            }
        });

        jLabel18.setText("Quantidade de Clientes encontrados:");

        labelQtdeClientePf.setText("     ");

        javax.swing.GroupLayout jPanelAcoesLayout = new javax.swing.GroupLayout(jPanelAcoes);
        jPanelAcoes.setLayout(jPanelAcoesLayout);
        jPanelAcoesLayout.setHorizontalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAcoesLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAbaConsultaPesquisar))
                    .addGroup(jPanelAcoesLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelQtdeClientePf)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAcoesLayout.setVerticalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAbaConsultaPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(labelQtdeClientePf))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelDadosClientePf, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                            .addComponent(jPanelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDadosClientePf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelTabela.getAccessibleContext().setAccessibleName("Dados Pessoais");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableClientePf.getSelectedRow() != -1) {
            ClientePf clientePf = new ClientePf();
            clientePf.setId(Integer.parseInt(tfId.getText()));
            if (rbJpa.isSelected()) {
                if (ClientePfJpaDao.getInstance().delete(clientePf)) {
                    JOptionPane.showMessageDialog(this, "ClientePf deletado com sucesso");
                    preencheTabela();
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Não foi possível deletar o funcionário id: " + clientePf.getId());
                }
            } else {
                if (ClientePfJdbcDao.getInstance().delete(clientePf)) {
                    JOptionPane.showMessageDialog(this, "ClientePf deletado com sucesso");
                    preencheTabela();
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Não foi possível deletar o funcionário id: " + clientePf.getId());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um ClientePf para deletar");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // Limpa os campos
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (!CamposEmBranco()) {
            ClientePf clientePf = new ClientePf();
            Endereco endereco = new Endereco();
            clientePf.setCpf(ftfCpf.getText().replace("-", "").replace(".", ""));
            clientePf.setNome(tfNome.getText());
            clientePf.setTelefone(ftfTelefone.getText().replace("(", "").replace(")", "").replace("-", ""));
            clientePf.setEmail(tfEmail.getText());
            endereco.setCEP(ftfCep.getText().replace("-", ""));
            endereco.setLogradouro(tfLogradouro.getText());
            endereco.setNumero(tfNumero.getText());
            endereco.setComplemento(tfComplemento.getText());
            endereco.setBairro(tfBairro.getText());
            endereco.setCidade(tfCidade.getText());
            endereco.setUf(jComboBoxEstado.getSelectedItem().toString());
            clientePf.setEndereco(endereco);
            if (rbJpa.isSelected()) {
                if (ClientePfJpaDao.getInstance().create(clientePf)) {
                    JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                    preencheTabela();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar");
                }
            } else {
                if (ClientePfJdbcDao.getInstance().create(clientePf)) {
                    JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                    preencheTabela();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar");
                }

            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        if (!CamposEmBranco()) {
            if (jTableClientePf.getSelectedRow() != -1) {
                ClientePf clientePf = ClientePfJpaDao.getInstance().getById(Integer.parseInt(tfId.getText()));
                Endereco endereco = new Endereco();
                clientePf.setCpf(ftfCpf.getText().replace("-", "").replace(".", ""));
                clientePf.setNome(tfNome.getText());
                clientePf.setTelefone(ftfTelefone.getText().replace("(", "").replace(")", "").replace("-", ""));
                clientePf.setEmail(tfEmail.getText());
                endereco.setCEP(ftfCep.getText().replace("-", ""));
                endereco.setLogradouro(tfLogradouro.getText());
                endereco.setNumero(tfNumero.getText());
                endereco.setComplemento(tfComplemento.getText());
                endereco.setBairro(tfBairro.getText());
                endereco.setCidade(tfCidade.getText());
                endereco.setUf(jComboBoxEstado.getSelectedItem().toString());
                clientePf.setEndereco(endereco);
                if (rbJpa.isSelected()) {
                    if (ClientePfJpaDao.getInstance().update(clientePf)) {
                        JOptionPane.showMessageDialog(this, "ClientePf Alterado com sucesso");
                        preencheTabela();
                        limparCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Não foi possível alterar o funcionário id: " + clientePf.getId());
                    }
                } else {
                    if (ClientePfJdbcDao.getInstance().update(clientePf)) {
                        JOptionPane.showMessageDialog(this, "ClientePf Alterado com sucesso");
                        preencheTabela();
                        limparCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Não foi possível alterar o funcionário id: " + clientePf.getId());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um ClientePf para alterar");
            }
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        habilitaCampos(true);
        habilitaBotoes(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        habilitaBotoes(false);
        habilitaCampos(false);
        jButtonExcluir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableClientePfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientePfMouseClicked
        // TODO add your handling code here:
        preencheByJtable();
    }//GEN-LAST:event_jTableClientePfMouseClicked

    private void jTableClientePfMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientePfMouseReleased
        // TODO add your handling code here:
        preencheByJtable();
    }//GEN-LAST:event_jTableClientePfMouseReleased

    private void jButtonVerificaPendenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificaPendenciasActionPerformed
        // TODO add your handling code here:
        if (!CamposEmBranco()) {
            JOptionPane.showMessageDialog(this, "Nenhuma Pendência encontrada");
        }
    }//GEN-LAST:event_jButtonVerificaPendenciasActionPerformed

    private void jButtonFecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharJanelaActionPerformed

    private void jButtonPesquisaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaCepActionPerformed
        // TODO add your handling code here:
        pesquisaCEP(ftfCep.getText());
    }//GEN-LAST:event_jButtonPesquisaCepActionPerformed

    private void ftfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfCpfFocusLost
        // TODO add your handling code here:
        if (!ValidaCampos.getInstance().isCpf(ftfCpf.getText())) {
            JOptionPane.showMessageDialog(null, "CPF inválido");
            ftfCpf.requestFocus();
        }
    }//GEN-LAST:event_ftfCpfFocusLost

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_btListarActionPerformed

    private void jTableClientePfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableClientePfKeyPressed
        // TODO add your handling code here:
        preencheByJtable();
    }//GEN-LAST:event_jTableClientePfKeyPressed

    private void cbTipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoPesquisaActionPerformed

    private void btAbaConsultaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbaConsultaPesquisarActionPerformed
        // TODO add your handling code here:
        List<ClientePf> listaClientePf = null;
        if (!tfConsulta.getText().replaceAll(" ", "").equals("")) {
            switch (cbTipoPesquisa.getSelectedIndex()) {
                case 0:
                    labelQtdeClientePf.setText("0");
                    JOptionPane.showMessageDialog(null, "Selecione um tipo para pesquisar");
                    break;
                case 1:
                try {
                    ClientePf clientePf = null;
                    if (rbJpa.isSelected()) {
                        clientePf = ClientePfJpaDao.getInstance().getById(Integer.parseInt(tfConsulta.getText()));
                    } else {
                        clientePf = ClientePfJdbcDao.getInstance().getById(Integer.parseInt(tfConsulta.getText()));
                    }
                    labelQtdeClientePf.setText("1");
                    tableModel.limpaTabela();
                    tableModel.addRow(clientePf);
                    jTableClientePf.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                    TableColumnAdjuster tca = new TableColumnAdjuster(jTableClientePf);
                    tca.adjustColumns();
                    break;
                } catch (NumberFormatException e) {
                    labelQtdeClientePf.setText("0");
                    JOptionPane.showMessageDialog(null, "Cliente " + tfConsulta.getText() + " não foi localizado.");
                    break;
                }
                case 2:
                    try {
                    //List<ClientePf> listaClientePf = new ArrayList<>();
                    if (rbJpa.isSelected()) {
                        listaClientePf = ClientePfJpaDao.getInstance().getBy("nome", tfConsulta.getText());
                    } else {
                        listaClientePf = ClientePfJdbcDao.getInstance().getBy("nome", tfConsulta.getText());
                    }
                    labelQtdeClientePf.setText("1");
                    tableModel.limpaTabela();
                    for (ClientePf clientePf : listaClientePf) {
                        tableModel.addRow(clientePf);
                    }
                    jTableClientePf.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                    TableColumnAdjuster tca = new TableColumnAdjuster(jTableClientePf);
                    tca.adjustColumns();
                    break;
                } catch (NumberFormatException e) {
                    labelQtdeClientePf.setText("0");
                    JOptionPane.showMessageDialog(null, "Cliente " + tfConsulta.getText() + " não foi localizado.");
                    break;
                }
                default:
                    labelQtdeClientePf.setText("0");
                    JOptionPane.showMessageDialog(null, "Selecione um tipo para pesquisar");
                    break;
            }
        } else {
            labelQtdeClientePf.setText("0");
            JOptionPane.showMessageDialog(null, "Campo pesquisar não pode estar em branco");
        }
    }//GEN-LAST:event_btAbaConsultaPesquisarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbaConsultaPesquisar;
    private javax.swing.ButtonGroup btGroupPersistencia;
    private javax.swing.JButton btListar;
    private javax.swing.JComboBox<String> cbTipoPesquisa;
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JFormattedTextField ftfCpf;
    private javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFecharJanela;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisaCep;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVerificaPendencias;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelDadosClientePf;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JPanel jPanelTipoPersistencia;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientePf;
    private javax.swing.JLabel labelQtdeClientePf;
    private javax.swing.JRadioButton rbJpa;
    private javax.swing.JRadioButton rdJdbc;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfConsulta;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumero;
    // End of variables declaration//GEN-END:variables

    private void pesquisaCEP(String cep) {
        try {
            ViaCEPEndereco resultCEP = new ViaCEPClient().getEndereco(cep);
            tfLogradouro.setText(resultCEP.getLogradouro());
            tfComplemento.setText(resultCEP.getComplemento());
            tfBairro.setText(resultCEP.getBairro());
            tfCidade.setText(resultCEP.getLocalidade());
            jComboBoxEstado.setSelectedItem(resultCEP.getUf());
        } catch (IOException ex) {
            Logger.getLogger(TesteCEP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void preencheTabela() {
        limpaTabela();
        List<ClientePf> listaClientePf = null;
        if (rbJpa.isSelected()) {
            System.out.println("listou em jpa");
            listaClientePf = ClientePfJpaDao.getInstance().readAll();
        } else {
            System.out.println("listou em jdbc");
            listaClientePf = ClientePfJdbcDao.getInstance().readAll();
        }
        listaClientePf.forEach((clientePf) -> {
            tableModel.addRow(clientePf);
        });
        jTableClientePf.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTableClientePf);
        tca.adjustColumns();
        listaClientePf = null;
    }

    public void limpaTabela() {
        tableModel.limpaTabela();
    }

    public JTextField[] limparCampos() {
        JTextField[] campos = {tfId, ftfCpf, tfNome, ftfTelefone,
            tfEmail, ftfCep, tfLogradouro, tfNumero, tfComplemento,
            tfBairro, tfCidade};
        for (int i = 0; i < campos.length; i++) {
            campos[i].setText("");
        }
        jComboBoxEstado.setSelectedIndex(0);
        return campos;
    }

    public boolean CamposEmBranco() {
        int erros = 0;
        String cpfVazio = "   .   .   -  ";
        String cepVazio = "     -   ";
        String telVazio = "(  )     -    ";
        if (ftfCpf.getText().equals(cpfVazio)) {
            JOptionPane.showMessageDialog(this, "Campo CPF em branco, verifique");
            erros++;
        }
        if (ftfTelefone.getText().equals(telVazio)) {
            JOptionPane.showMessageDialog(this, "Campo Telefone em branco, verifique");
            erros++;
        }
        if (ftfCep.getText().equals(cepVazio)) {
            JOptionPane.showMessageDialog(this, "Campo CEP em branco, verifique");
            erros++;
        }
        JTextField[] campos = {tfNome, tfEmail,
            tfLogradouro, tfNumero, tfBairro, tfCidade};
        String[] camposNome = {"Nome", "E-Mail", "Logradouro",
            "Número", "Bairro", "Cidade"};
        for (int i = 0; i < campos.length; i++) {
            if (campos[i].getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Campo " + camposNome[i] + " em branco, verifique");
                erros++;
            }
        }
        if (jComboBoxEstado.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione a UF");
            erros++;
        }
        if (erros == 0) {
            return false;
        } else {
            return true;
        }
    }

    private void habilitaCampos(boolean estado) {
        JTextField[] listaCampos = {tfNome, tfEmail,
            tfLogradouro, tfComplemento, tfNumero, tfBairro, tfCidade};
        for (JTextField campos : listaCampos) {
            campos.setEnabled(estado);
        }
        JFormattedTextField[] listaCamposFormatados = {ftfCpf, ftfCep, ftfTelefone};
        for (JFormattedTextField camposFormatados : listaCamposFormatados) {
            camposFormatados.setEnabled(estado);
        }
        jComboBoxEstado.setEnabled(estado);
    }

    private void habilitaBotoes(boolean estado) {
        jButtonCancelar.setEnabled(estado);
        jButtonLimpar.setEnabled(estado);
        jButtonSalvar.setEnabled(estado);
        jButtonVerificaPendencias.setEnabled(estado);
        jButtonPesquisaCep.setEnabled(estado);
    }

    private void preencheByJtable() {
        if (jTableClientePf.getSelectedRow() != -1) {

            jButtonExcluir.setEnabled(true);
            jButtonAlterar.setEnabled(true);

            tfId.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 0).toString());
            ftfCpf.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 1).toString());
            tfNome.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 2).toString());
            ftfTelefone.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 3).toString());
            tfEmail.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 4).toString());
            ftfCep.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 5).toString());
            tfLogradouro.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 6).toString());
            tfNumero.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 7).toString());
            tfComplemento.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 8).toString());
            tfBairro.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 9).toString());
            tfCidade.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 10).toString());
            jComboBoxEstado.setSelectedItem(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 11).toString());
        }
    }
}
