package br.com.rftech.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// Import das classes para trabalhar com o preenchimento do endereço a partir do CEP


// Import de componentes da interface gráfica
import br.com.rftech.Dao.ClientePfJpaDao;
import br.com.rftech.bean.ClientePf;
import br.com.rftech.bean.ClientePfTableModel;
import br.com.rftech.bean.TableColumnAdjuster;
import br.com.rftech.controller.ClientePfController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo Fereira Rodrigues
 */
public class ClientePfView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientesPFView
     */
    public ClientePfView() {
        initComponents();
        jTableClientePf.setModel(tableModel);
        preencheTabela();

        //ajustaTabela();
        habilitaCampos(false);
        habilitaBotoes(false);
    }

    //Instancia minha jTable com base no modelo de Tabela definido no pacote MODEL
    ClientePfTableModel tableModel = new ClientePfTableModel();

    public void preencheTabela() {

        tableModel.limpaTabela();
        List<ClientePf> listaClientePf = ClientePfJpaDao.getInstance().readAll();
        for (ClientePf clientePf : listaClientePf) {
            tableModel.addRow(clientePf);
        }
        jTableClientePf.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTableClientePf);
        tca.adjustColumns();

    }

    public JTextField[] limparCampos() {
        JTextField[] campos = {tfNome, tfId};
        for (int i = 0; i < campos.length; i++) {
            campos[i].setText("");
        }
        return campos;
    }

    public boolean verificaCamposEmBranco() {
        int erros = 0;
        String cepvazio = "     -   ";
        String telvazio = "(  )       -     ";
        JTextField[] campos = { tfNome};
        String[] camposNome = {"ClientePf", "Obs"};
        for (int i = 0; i < campos.length; i++) {
            if (campos[i].getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Campo " + camposNome[i] + " em branco, verifique");
                erros++;
            }
        }
        if (erros == 0) {
            return true;
        } else {
            return false;
        }
    }

    private void habilitaCampos(boolean estado) {

        tfCpf.setEnabled(estado);
        tfNome.setEnabled(estado);
    }

    private void habilitaBotoes(boolean estado) {
        jButtonAlterar.setEnabled(estado);
        jButtonCancelar.setEnabled(estado);
        jButtonExcluir.setEnabled(estado);
        jButtonLimpar.setEnabled(estado);
        jButtonSalvar.setEnabled(estado);
        jButtonVerificaPendencias.setEnabled(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDadosFabricantes = new javax.swing.JPanel();
        tfCpf = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientePf = new javax.swing.JTable();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonConsulta = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVerificaPendencias = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFecharJanela = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(787, 412));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelDadosFabricantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        jPanelDadosFabricantes.setPreferredSize(new java.awt.Dimension(787, 412));

        tfCpf.setText("000.000.000-00");
        tfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCpfFocusLost(evt);
            }
        });
        tfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfActionPerformed(evt);
            }
        });

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfId.setEditable(false);

        jLabelCPF.setText("CPF:");

        jLabelNome.setText("Nome:");

        jLabelId.setText("ID:");

        javax.swing.GroupLayout jPanelDadosFabricantesLayout = new javax.swing.GroupLayout(jPanelDadosFabricantes);
        jPanelDadosFabricantes.setLayout(jPanelDadosFabricantesLayout);
        jPanelDadosFabricantesLayout.setHorizontalGroup(
            jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 113, Short.MAX_VALUE))
        );
        jPanelDadosFabricantesLayout.setVerticalGroup(
            jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFabricantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Clientes Pessoa Física"));

        jTableClientePf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HP", "Garantia pelo Fabricante"}
            },
            new String [] {
                "Cód", "Fabricante", "Obs"
            }
        ));
        jTableClientePf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientePfMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableClientePfMouseReleased(evt);
            }
        });
        jTableClientePf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableClientePfKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientePf);

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonConsulta.setText("Consultar");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar Campos");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVerificaPendencias.setText("Verifica Pendências");
        jButtonVerificaPendencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificaPendenciasActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFecharJanela.setText("Fechar");
        jButtonFecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharJanelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerificaPendencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFecharJanela)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAlterar)
                        .addComponent(jButtonLimpar)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonFecharJanela)
                        .addComponent(jButtonExcluir)
                        .addComponent(jButtonVerificaPendencias))
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo)
                        .addComponent(jButtonCancelar))
                    .addComponent(jButtonConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDadosFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDadosFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelTabela.getAccessibleContext().setAccessibleName("Dados Pessoais");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableClientePf.getSelectedRow() != -1) {
            ClientePfController fabCtrl = new ClientePfController();
            ClientePf clientePf = new ClientePf();
            clientePf.setId(Integer.parseInt(tfId.getText()));
            clientePf.setNome(tfCpf.getText());
            clientePf.setEmail(tfNome.getText());
            if (fabCtrl.delete(clientePf)) {
                JOptionPane.showMessageDialog(this, "ClientePf deletado com sucesso");
                preencheTabela();
                limparCampos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um ClientePf para deletar");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
        // Acessando direto pelo Controller
        preencheTabela();
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Banco de dados vazio");
        }
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // Limpa os campos
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        ClientePfController fabCtrl = new ClientePfController();
        ClientePf clientePf = new ClientePf();
        clientePf.setNome(tfCpf.getText());
        clientePf.setEmail(tfNome.getText());
        if (fabCtrl.create(clientePf)) {
            JOptionPane.showMessageDialog(this, "Salvo com sucesso");
            preencheTabela();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        if (jTableClientePf.getSelectedRow() != -1) {
            ClientePfController fabCtrl = new ClientePfController();
            ClientePf clientePf = new ClientePf();
            clientePf.setId(Integer.parseInt(tfId.getText()));
            clientePf.setNome(tfCpf.getText());
            clientePf.setEmail(tfNome.getText());
            if (fabCtrl.update(clientePf)) {
                JOptionPane.showMessageDialog(this, "ClientePf Alterado com sucesso");
                preencheTabela();
                limparCampos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um ClientePf para alterar");
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        habilitaCampos(true);
        habilitaBotoes(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        habilitaBotoes(false);
        habilitaCampos(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableClientePfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientePfMouseClicked
        // TODO add your handling code here:
        if (jTableClientePf.getSelectedRow() != -1) {
            tfId.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 0).toString());
            tfCpf.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 1).toString());
            tfNome.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jTableClientePfMouseClicked

    private void jTableClientePfMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientePfMouseReleased
        // TODO add your handling code here:
        if (jTableClientePf.getSelectedRow() != -1) {
            tfId.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 0).toString());
            tfCpf.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 1).toString());
            tfNome.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jTableClientePfMouseReleased

    private void jTableClientePfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableClientePfKeyReleased
        // TODO add your handling code here:
        if (jTableClientePf.getSelectedRow() != -1) {
            tfId.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 0).toString());
            tfCpf.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 1).toString());
            tfNome.setText(jTableClientePf.getValueAt(jTableClientePf.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jTableClientePfKeyReleased

    private void tfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_tfCpfFocusLost

    private void jButtonVerificaPendenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificaPendenciasActionPerformed
        // TODO add your handling code here:
        if (verificaCamposEmBranco()) {
            JOptionPane.showMessageDialog(this, "Nenhuma Pendência encontrada");
        }
    }//GEN-LAST:event_jButtonVerificaPendenciasActionPerformed

    private void jButtonFecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharJanelaActionPerformed

    private void tfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFecharJanela;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVerificaPendencias;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelDadosFabricantes;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientePf;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
