/*
 * The MIT License
 *
 * Copyright 2019 Rodrigo Ferreira Rodrigues <https://github.com/rfrodriguespe>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.rftech.view;

import br.com.rftech.Dao.FornecedorJpaDao;
import br.com.rftech.Dao.CargoJpaDao;
import br.com.rftech.bean.Fornecedor;
import br.com.rftech.bean.FornecedorTableModel;
import br.com.rftech.bean.Cargo;
import br.com.rftech.bean.Endereco;
import br.com.rftech.bean.TableColumnAdjuster;
import br.com.rftech.testes.TesteCEP;
import br.com.rftech.util.ValidaCampos;
import com.github.gilbertotorrezan.viacep.se.ViaCEPClient;
import com.github.gilbertotorrezan.viacep.shared.ViaCEPEndereco;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo Ferreira Rodrigues <https://github.com/rfrodriguespe>
 */
public class FornecedorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientesPFView
     */
    public FornecedorView() {
        initComponents();
        jTableClientePj.setModel(tableModel);
        preencheTabela();
        habilitaCampos(false);
    }

    //Instancia minha jTable com base no modelo de Tabela definido no pacote MODEL
    FornecedorTableModel tableModel = new FornecedorTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDadosFuncionario = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        ftfCnpj = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftfTelefone = new javax.swing.JFormattedTextField();
        tfEmail = new javax.swing.JTextField();
        jLabelNome1 = new javax.swing.JLabel();
        tfRazaoSocial = new javax.swing.JTextField();
        jLabelNome2 = new javax.swing.JLabel();
        tfNomeContato = new javax.swing.JTextField();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientePj = new javax.swing.JTable();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVerificaPendencias = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFecharJanela = new javax.swing.JButton();
        jPanelEndereco = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ftfCep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonPesquisaCep = new javax.swing.JButton();
        jComboBoxEstado = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(787, 412));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelDadosFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        jPanelDadosFuncionario.setPreferredSize(new java.awt.Dimension(787, 412));

        tfNome.setEnabled(false);
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfId.setEditable(false);

        jLabelCPF.setText("CNPJ:");

        jLabelNome.setText("Nome:");

        jLabelId.setText("ID:");

        try {
            ftfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.##/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCnpj.setEnabled(false);
        ftfCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfCnpjFocusLost(evt);
            }
        });

        jLabel4.setText("Telefone:");

        jLabel5.setText("E-mail:");

        try {
            ftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfTelefone.setEnabled(false);

        tfEmail.setEnabled(false);

        jLabelNome1.setText("Razaão Social");

        tfRazaoSocial.setEnabled(false);
        tfRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRazaoSocialActionPerformed(evt);
            }
        });

        jLabelNome2.setText("Nome do Contato:");

        tfNomeContato.setEnabled(false);
        tfNomeContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeContatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosFuncionarioLayout = new javax.swing.GroupLayout(jPanelDadosFuncionario);
        jPanelDadosFuncionario.setLayout(jPanelDadosFuncionarioLayout);
        jPanelDadosFuncionarioLayout.setHorizontalGroup(
            jPanelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome))
                    .addGroup(jPanelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail))
                    .addGroup(jPanelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabelNome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                    .addGroup(jPanelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabelNome2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeContato, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))))
        );
        jPanelDadosFuncionarioLayout.setVerticalGroup(
            jPanelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF)
                    .addComponent(ftfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome1)
                    .addComponent(tfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome2)
                    .addComponent(tfNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Fornecedores"));

        jTableClientePj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HP", "Garantia pelo Fabricante"}
            },
            new String [] {
                "Cód", "Fabricante", "Obs"
            }
        ));
        jTableClientePj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientePjMouseClicked(evt);
            }
        });
        jTableClientePj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableClientePjKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientePj);

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar Campos");
        jButtonLimpar.setEnabled(false);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVerificaPendencias.setText("Verifica Pendências");
        jButtonVerificaPendencias.setEnabled(false);
        jButtonVerificaPendencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificaPendenciasActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFecharJanela.setText("Fechar");
        jButtonFecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharJanelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVerificaPendencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFecharJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerificaPendencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharJanela)
                .addContainerGap())
        );

        jPanelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel6.setText("CEP:");

        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCep.setEnabled(false);

        jLabel7.setText("Logradouro");

        tfLogradouro.setEnabled(false);

        jLabel8.setText("Número:");

        tfNumero.setEnabled(false);

        tfComplemento.setEnabled(false);

        jLabel9.setText("Complemento");

        jLabel10.setText("Bairro");

        tfBairro.setEnabled(false);

        jLabel11.setText("Cidade");

        tfCidade.setEnabled(false);

        jLabel12.setText("UF");

        jButtonPesquisaCep.setText("Pesquisa CEP");
        jButtonPesquisaCep.setEnabled(false);
        jButtonPesquisaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaCepActionPerformed(evt);
            }
        });

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxEstado.setToolTipText("");
        jComboBoxEstado.setEnabled(false);

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLogradouro))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisaCep)
                    .addComponent(jLabel7)
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelDadosFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addComponent(jPanelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDadosFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanelTabela.getAccessibleContext().setAccessibleName("Dados Pessoais");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableClientePj.getSelectedRow() != -1) {
            Fornecedor clientePj = new Fornecedor();
            clientePj.setId(Integer.parseInt(tfId.getText()));
            if (FornecedorJpaDao.getInstance().delete(clientePj)) {
                JOptionPane.showMessageDialog(this, "ClientePj deletado com sucesso");
                preencheTabela();
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível deletar o funcionário id: " + clientePj.getId());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um ClientePj para deletar");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // Limpa os campos
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (!CamposEmBranco()) {
            Fornecedor clientePj = new Fornecedor();
            Endereco endereco = new Endereco();
            clientePj.setCnpj(ftfCnpj.getText().replace("-", "").replace(".", "").replace("/", ""));
            clientePj.setNome(tfNome.getText());
            clientePj.setRazaoSocial(tfRazaoSocial.getText());
            clientePj.setNomeContato(tfNomeContato.getText());
            clientePj.setTelefone(ftfTelefone.getText().replace("(", "").replace(")", "").replace("-", ""));
            clientePj.setEmail(tfEmail.getText());
            endereco.setCEP(ftfCep.getText().replace("-", ""));
            endereco.setLogradouro(tfLogradouro.getText());
            endereco.setNumero(tfNumero.getText());
            endereco.setComplemento(tfComplemento.getText());
            endereco.setBairro(tfBairro.getText());
            endereco.setCidade(tfCidade.getText());
            endereco.setUf(jComboBoxEstado.getSelectedItem().toString());
            clientePj.setEndereco(endereco);
            if (FornecedorJpaDao.getInstance().create(clientePj)) {
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                preencheTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        if (!CamposEmBranco()) {
            if (jTableClientePj.getSelectedRow() != -1) {
                Fornecedor clientePj = FornecedorJpaDao.getInstance().getById(Integer.parseInt(tfId.getText()));
                Endereco endereco = new Endereco();
                clientePj.setCnpj(ftfCnpj.getText().replace("-", "").replace(".", "").replace("/", ""));
                clientePj.setNome(tfNome.getText());
                clientePj.setRazaoSocial(tfRazaoSocial.getText());
                clientePj.setNomeContato(tfNomeContato.getText());
                clientePj.setTelefone(ftfTelefone.getText().replace("(", "").replace(")", "").replace("-", ""));
                clientePj.setEmail(tfEmail.getText());
                endereco.setCEP(ftfCep.getText().replace("-", ""));
                endereco.setLogradouro(tfLogradouro.getText());
                endereco.setNumero(tfNumero.getText());
                endereco.setComplemento(tfComplemento.getText());
                endereco.setBairro(tfBairro.getText());
                endereco.setCidade(tfCidade.getText());
                endereco.setUf(jComboBoxEstado.getSelectedItem().toString());
                clientePj.setEndereco(endereco);
                if (FornecedorJpaDao.getInstance().update(clientePj)) {
                    JOptionPane.showMessageDialog(this, "ClientePj Alterado com sucesso");
                    preencheTabela();
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Não foi possível alterar o funcionário id: " + clientePj.getId());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um ClientePj para alterar");
            }
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        habilitaCampos(true);
        habilitaBotoes(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        habilitaBotoes(false);
        habilitaCampos(false);
        jButtonExcluir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        limparCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableClientePjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientePjMouseClicked
        // TODO add your handling code here:
        if (jTableClientePj.getSelectedRow() != -1) {

            jButtonExcluir.setEnabled(true);
            jButtonAlterar.setEnabled(true);

            tfId.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 0).toString());
            ftfCnpj.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 1).toString());
            tfNome.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 2).toString());
            tfRazaoSocial.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 3).toString());
            tfNomeContato.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 4).toString());
            ftfTelefone.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 5).toString());
            tfEmail.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 6).toString());
            ftfCep.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 7).toString());
            tfLogradouro.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 8).toString());
            tfNumero.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 9).toString());
            tfComplemento.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 10).toString());
            tfBairro.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 11).toString());
            tfCidade.setText(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 12).toString());
            jComboBoxEstado.setSelectedItem(jTableClientePj.getValueAt(jTableClientePj.getSelectedRow(), 13).toString());
        }
    }//GEN-LAST:event_jTableClientePjMouseClicked

    private void jButtonVerificaPendenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificaPendenciasActionPerformed
        // TODO add your handling code here:
        if (!CamposEmBranco()) {
            JOptionPane.showMessageDialog(this, "Nenhuma Pendência encontrada");
        }
    }//GEN-LAST:event_jButtonVerificaPendenciasActionPerformed

    private void jButtonFecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharJanelaActionPerformed

    private void jButtonPesquisaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaCepActionPerformed
        // TODO add your handling code here:
        pesquisaCEP(ftfCep.getText());
    }//GEN-LAST:event_jButtonPesquisaCepActionPerformed

    private void ftfCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfCnpjFocusLost
        // TODO add your handling code here:
        if (!ValidaCampos.getInstance().isCnpj(ftfCnpj.getText())) {
            JOptionPane.showMessageDialog(null, "CNPJ inválido");
            ftfCnpj.requestFocus();
        }
    }//GEN-LAST:event_ftfCnpjFocusLost

    private void tfRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRazaoSocialActionPerformed

    private void tfNomeContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeContatoActionPerformed

    private void jTableClientePjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableClientePjKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableClientePjKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JFormattedTextField ftfCnpj;
    private javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFecharJanela;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisaCep;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVerificaPendencias;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelDadosFuncionario;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientePj;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeContato;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfRazaoSocial;
    // End of variables declaration//GEN-END:variables

    private void pesquisaCEP(String cep) {
        try {
            ViaCEPEndereco resultCEP = new ViaCEPClient().getEndereco(cep);
            tfLogradouro.setText(resultCEP.getLogradouro());
            tfComplemento.setText(resultCEP.getComplemento());
            tfBairro.setText(resultCEP.getBairro());
            tfCidade.setText(resultCEP.getLocalidade());
            jComboBoxEstado.setSelectedItem(resultCEP.getUf());
        } catch (IOException ex) {
            Logger.getLogger(TesteCEP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void preencheTabela() {
        limpaTabela();
        List<Fornecedor> listaClientePj = FornecedorJpaDao.getInstance().readAll();
        listaClientePj.forEach((clientePj) -> {
            tableModel.addRow(clientePj);
        });
        jTableClientePj.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTableClientePj);
        tca.adjustColumns();
        listaClientePj = null;
    }

    public void limpaTabela() {
        tableModel.limpaTabela();
    }

    public JTextField[] limparCampos() {
        JTextField[] campos = {tfId, ftfCnpj, tfNome, tfRazaoSocial, tfNomeContato,
            ftfTelefone, tfEmail, ftfCep, tfLogradouro, tfNumero, tfComplemento,
            tfBairro, tfCidade};
        for (int i = 0; i < campos.length; i++) {
            campos[i].setText("");
        }
        jComboBoxEstado.setSelectedIndex(0);
        return campos;
    }

    public boolean CamposEmBranco() {
        int erros = 0;
        String cpfVazio = "   .   .  /    -  ";
        String cepVazio = "     -   ";
        String telVazio = "(  )     -    ";
        if (ftfCnpj.getText().equals(cpfVazio)) {
            JOptionPane.showMessageDialog(this, "Campo Cnpj em branco, verifique");
            erros++;
        }
        if (ftfTelefone.getText().equals(telVazio)) {
            JOptionPane.showMessageDialog(this, "Campo Telefone em branco, verifique");
            erros++;
        }
        if (ftfCep.getText().equals(cepVazio)) {
            JOptionPane.showMessageDialog(this, "Campo CEP em branco, verifique");
            erros++;
        }
        JTextField[] campos = {tfNome, tfRazaoSocial, tfNomeContato, tfEmail,
            tfLogradouro, tfNumero, tfBairro, tfCidade};
        String[] camposNome = {"Nome", "Razão Social", "Nome do Contato", "E-Mail", "Logradouro",
            "Número", "Bairro", "Cidade"};
        for (int i = 0; i < campos.length; i++) {
            if (campos[i].getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Campo " + camposNome[i] + " em branco, verifique");
                erros++;
            }
        }
        if (jComboBoxEstado.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione a UF");
            erros++;
        }
        if (erros == 0) {
            return false;
        } else {
            return true;
        }
    }

    private void habilitaCampos(boolean estado) {
        JTextField[] listaCampos = {tfNome, tfRazaoSocial, tfNomeContato, tfEmail,
            tfLogradouro, tfComplemento, tfNumero, tfBairro, tfCidade};
        for (JTextField campos : listaCampos) {
            campos.setEnabled(estado);
        }
        JFormattedTextField[] listaCamposFormatados = {ftfCnpj, ftfCep, ftfTelefone};
        for (JFormattedTextField camposFormatados : listaCamposFormatados) {
            camposFormatados.setEnabled(estado);
        }
        jComboBoxEstado.setEnabled(estado);
    }

    private void habilitaBotoes(boolean estado) {
        jButtonCancelar.setEnabled(estado);
        jButtonLimpar.setEnabled(estado);
        jButtonSalvar.setEnabled(estado);
        jButtonVerificaPendencias.setEnabled(estado);
        jButtonPesquisaCep.setEnabled(estado);
    }
}
